
set(PLAT_SRC_DIR ${PX4_SOURCE_DIR}/.. CACHE FILEPATH "PLAT source directory" FORCE)
set(PLAT_BOARD_CONFIG_DIR ${PX4_BOARD_DIR})

string(REGEX REPLACE ".*/([^/]+/[^/]+)$" "\\1" BOARD_CONFIG_RELATIVE_PATH ${PLAT_BOARD_CONFIG_DIR})
message("${BOARD_CONFIG_RELATIVE_PATH}")
message("PLAT_BOARD_CONFIG_DIR=${PLAT_BOARD_CONFIG_DIR}")

set(BOARD_NEW_CONFIG ${PLAT_SRC_DIR}/boards/${BOARD_CONFIG_RELATIVE_PATH} CACHE FILEPATH "PLAT board config path" FORCE)
message("${BOARD_NEW_CONFIG}")

file(COPY "${BOARD_NEW_CONFIG}/default.px4board" DESTINATION "${PLAT_BOARD_CONFIG_DIR}" FOLLOW_SYMLINK_CHAIN)

